name: commercial_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-257.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  flutter_screenutil: ^5.6.0
  cupertino_icons: ^1.0.2
  shimmer: ^2.0.0

  #Firebase
  firebase_auth: ^4.1.4
  firebase_storage: ^11.0.6
  firebase_core: ^2.3.0
  
  #Data
  json_serializable: ^6.3.1
  http: ^0.13.5
   
  #Other
  flutter_bloc: ^8.1.1
  sqflite: ^2.2.0+3
  flutter_svg: ^1.1.6
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: Neom
      fonts:
        - asset: assets/fonts/Neom.ttf
        - asset: assets/fonts/Neom.otf
